# Name: Faizan Ali
# Roll No: PIAIC 81615
# Quater :2
# Instructor: Sir Qasim

# Assignment




## Import Numpy

In [1]:
import numpy as np

## array()

In [3]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a)

[0 1 2 3 4 5 6 7 8 9]


## 2- arange() 

In [4]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


## 3-ndim() 

In [5]:
b=np.ndim(a)
print(b)

1


## 4-reshape()

In [9]:
c=np.arange(10).reshape(5,2)
print(c)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## 5-shape

In [19]:
a=np.array([[1,2,3],[4,5,6]]).shape
print(a)

(2, 3)


## 6- swapaxes()

In [26]:
a=np.arange(10).reshape(5,2)
print(a)
b=np.swapaxes(a,0,1)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


## 7-asfarray()

In [40]:
a=np.arange(10)
b=np.asfarray(a)
print(b)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 8-arround()

In [41]:
a=np.array([2.559,2.00588,3.5581,8.0646,5.2587])
b=np.around(a,1)
print(b)

[2.6 2.  3.6 8.1 5.3]


## 9-trunc()

In [42]:
print(np.trunc(a))

[2. 2. 3. 8. 5.]


## 10-flipud()

In [46]:
a=np.arange(10)
print(a)
b=np.flipud(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


## 11-add() 

In [51]:
x=[1,2,3,4,5]
y=[6,7,8,9,10]
print(x)
print(y)
z=np.add(x,y)
print(z)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[ 7  9 11 13 15]


## 12-subtract()

In [54]:
print(np.subtract(y,x))

[5 5 5 5 5]


## 13-multiply()

In [55]:
print(np.multiply(x,y))

[ 6 14 24 36 50]


## 14-divide()

In [57]:
print(np.divide(y,x))

[6.         3.5        2.66666667 2.25       2.        ]


##  15-power()

In [58]:
print(np.power(x,y))

[      1     128    6561  262144 9765625]


## 16-mod()

In [60]:
print(np.mod(y,x))

[0 1 2 1 0]


## 17-divmod()

In [61]:
print(np.divmod(x,y))

(array([0, 0, 0, 0, 0], dtype=int32), array([1, 2, 3, 4, 5], dtype=int32))


## 18-floor() 

In [64]:
a=[2.05,5.025,5.660,8.458]
b=np.floor(a)
print(b)

[2. 5. 5. 8.]


## 19-ceil()

In [65]:
print(np.ceil(a))

[3. 6. 6. 9.]


## 20-log2()

In [68]:
a=np.arange(1,11)
b=np.log2(a)
print(b)

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925   3.32192809]


## 21-log10() 

In [69]:
print(np.log10(a))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ]


## 22- log() 

In [70]:
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 23-where() 

In [74]:
a=np.arange(10)
b=np.where(a%2!=0)
print(b)

(array([1, 3, 5, 7, 9], dtype=int64),)


## 24-searchsorted()

In [76]:
print(np.searchsorted(a,5))

5


## 25-random.rand()

In [82]:
a=np.random.rand(10)
print(a)

[0.05767945 0.19193774 0.04835461 0.16507425 0.62660739 0.23081025
 0.24736099 0.52005648 0.43083626 0.57854161]


## 26-random.randint()

In [84]:
a=np.random.randint(20,size=[10])
print(a)

[ 2 19 17 13  8  1  4  8 14 10]


## 27-sort() 

In [85]:
print(np.sort(a))

[ 1  2  4  8  8 10 13 14 17 19]


## 28-unique() 

In [90]:
names=np.array(['Faizan', 'Tahir Waseem','Faizan','Tahir Waseem'])
b=np.unique(names)
print(b)

['Faizan' 'Tahir Waseem']


## 29-slicing()

In [96]:
a=np.arange(10)
print(a)
print(a[3:5])

[0 1 2 3 4 5 6 7 8 9]
[3 4]


## 30-array_split()

In [98]:
a = np.array([1, 2, 3, 4, 5, 6])
b= np.array_split(a, 3)
print(b)

[array([1, 2]), array([3, 4]), array([5, 6])]


## 31-flip()

# a=np.arange(20).reshape(4,5)
a
np.flip(a,1)

## 32-dot()

In [101]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

## 33-zeros ()

In [102]:
x=np.zeros(15)   
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 34-max()

In [106]:
a=np.random.randint(12,size=(5))
print(a)
b=a.max(axis=0)
print(b)

[9 4 0 7 0]
9


## 35-min()

In [107]:
a=np.random.randint(12,size=(5))
print(a)
b=a.min(axis=0)
print(b)

[1 7 5 7 1]
1


## 36-setdiff

In [109]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,7,8,9])
result=np.setdiff1d(a,b)
print(result)

[1 2 3]


## 37-signbit()

In [112]:
a=np.signbit(-1.2)
b=np.signbit(np.array([1, -2.3, 2.1]))
print(b)

[False  True False]


## 38-reciprocal() 

In [116]:
a=np.reciprocal([2.,5.,3.5])
print(a)

[0.5        0.2        0.28571429]


## 39-nditer()

In [117]:
arr=np.arange(8).reshape(2,2,2)
for x in np.nditer(arr):
  print(x)


0
1
2
3
4
5
6
7


## 40-ndenumerate


In [118]:
for x in np.ndenumerate(arr):
    print(x)


((0, 0, 0), 0)
((0, 0, 1), 1)
((0, 1, 0), 2)
((0, 1, 1), 3)
((1, 0, 0), 4)
((1, 0, 1), 5)
((1, 1, 0), 6)
((1, 1, 1), 7)


## 41-copy()

In [119]:
arr=np.arange(10)
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  1  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]


## 42-veiw()

In [120]:
arr=np.arange(10)
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  1  2  3  4  5  6  7  8  9]
[42  1  2  3  4  5  6  7  8  9]


## 43-reduce()

In [121]:
arr=np.arange(3,4,7)
x=np.lcm.reduce(arr)
print(arr)
print(x)


[3]
3


## 44-sin()

In [122]:
x=np.sin(np.pi/2)
print(x)

1.0


## 45deg2rad()

In [123]:
arr=np.array([90, 180, 270, 360])
x=np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]



## 46-acrsin()

In [127]:
x=np.arcsin(1.0)
print(x)

1.5707963267948966


## 47-hypot

In [129]:
x=10
y=40
z=np.hypot(x,y)
print(z)

41.23105625617661


## 48-absolute()

In [130]:
arr=np.array([-1, -2, 1, 2, 3, -4])
newarr=np.absolute(arr)
print(newarr)


[1 2 1 2 3 4]


## 49-fix() 

In [131]:
arr=np.fix([-3.1666, 3.6667])
print(arr)

[-3.  3.]


## 50-cumsum()

In [132]:
arr = np.array([1, 2, 3])
newarr = np.cumsum(arr)
print(newarr)

[1 3 6]


# The END